# Generated by Django 6.0.2 on 2026-09-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pickup_state', models.CharField(max_length=100)),
                ('cargo_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
